### ISSUE TITLE
Gulp-ify the theme

### ISSUE THREAD

**Issue by advancedwpuser** [advancedwp/awp-2015#2]
I'd prefer to ditch bower all together and simply keep the theme purely SASS/Gulp. Would love a PR from an experienced Gulp-er to make that happen.

**Comment by michaelbeil** [comment]
Fixed with https://github.com/advancedwp/awp-2015/commit/9db451957de623f5e6aff3d0663f9bf3ca9203a7.

**Comment by mathetos** [comment]
Ha! Good catch. @michaelbeil Would love your contributions here. Have any plans to jump in and help out? How would you most like to help?
